### PR TITLE
Change link-no-permission to something a bit less confusing

### LINKED ISSUE #50: Redo the link-no-permission error message to be a bit easier to understand
It was brought to my attention over on the spigot resources page that the error message for when a key cannot be linked was a bit too confusing. Having considered it, I think it would likely be wise to redo and re-translate it so that players understand the intent more clearly.

The wording of this new message has yet to be determined. Any suggestions are welcome. For context, this was the previous error message.

https://github.com/AtriusX/Waystones/blob/bb18cbb6f7333dc5c60e756470852ab5bd6b0aca/src/main/resources/locale-en.yml#L41

### PR DESCRIPTION
**Pull request by AtriusX**
Closes #50

This change was made by the request of someone over on the spigot resource page. I noticed this appeared to be a common issue so I felt it was likely a wise choice to update this message to be a bit easier to understand.

@NewbieOrange Does the new message appear to be a bit better to you? If you have any suggestions please let me know, otherwise I would appreciate it if you could update the corresponding translation for `locale-cn` as well. Thanks!

### CODE REVIEW

**Comment by NewbieOrange** [comment]
The Chinese localization is very straight forward on this one, means exactly `You have no permission to teleport` 😄

**Comment by AtriusX** [comment]
I see, so it needs no adjustment in your mind then?

**Comment by NewbieOrange** [comment]
Yep

**Comment by AtriusX** [comment]
Alright! I'll mark this as ready and leave it for another day or so before merging just in case other people have alternative ideas to share.

**Pull request merged**
