### PR TITLE
Merge restructure into master branch

### PR DESCRIPTION
**Pull request by AtriusX**
Some review is still needed on this before merging, but it should otherwise merge without issues.

### CODE REVIEW

**Comment by Sepshun** [comment]
This all looks good imo!
I'm going to build the PR and test a bit as well as check if the commands are still working, as that's the one thing I've neglected to test.

**Comment by AtriusX** [comment]
Ok, lmk if any other problems occur!

**Comment by Sepshun** [comment]
Everything seems to be working as intended, no bugs through any of my testing! I think it's good to go :)

**Comment by AtriusX** [comment]
Merging into master now then!

**Pull request merged**
