### PR TITLE
Add support for custom advancements

### PR DESCRIPTION
**Pull request by AtriusX**
This PR adds a series of custom advancements to the plugin, as well as a few bug fixes. Currently the plugin includes 10 advancements, with one being unused (likely will be used in later updates). An update to the `reload` command has also been introduced for reloading advancements due to data loss issues related to how spigot and paper handle registering advancements.

As it stands, localization still needs to be done for the advancement messages. @NewbieOrange If you have time your help would be greatly appreciated.

### CODE REVIEW

**Comment by AtriusX** [comment]
@NewbieOrange Just double checking, are you available?

**Comment by NewbieOrange** [comment]
> @NewbieOrange Just double checking, are you available?

Sure, will add localizations after this is finalized.

**Comment by AtriusX** [comment]
Great, thanks! The PR should be pretty much good to go I think. I started moving on to `fix/world-ratio` after this so I believe this one is pretty much ready. Will also likely need a few translations for that branch as well once its ready, just as a heads up.

**Comment by AtriusX** [comment]
@NewbieOrange Sorry for the delay, both this and #37 are more or less ready so you can translate them now.

**Pull request merged**
