### PR TITLE
Add dynamic key recipe to configuration

### PR DESCRIPTION
**Pull request by AtriusX**
This PR adds the ability to determine a custom crafting recipe for warp keys as requested by #26. Crafting recipes are defined by the `key-recipe` property in the configuration file in the format of `[ "item1", "item2", "item3" ]`. Acceptable lengths for this list are 1, 4, or 9 (corresponding to the squares of 1, 2, and 3). Each item in this list should correspond to the name of a value in the  `Material` enum.

Testing was done locally and it appears to function, however further testing should be done to make sure it behaves properly and as expected.

### CODE REVIEW

**Comment by AtriusX** [comment]
@NathanAdhitya If you would like you can test this out.

**Comment by NathanAdhitya** [comment]
> @NathanAdhitya If you would like you can test this out.
I have never compiled a kotlin project myself, this is going to be a challenge. 🤣

**Comment by NathanAdhitya** [comment]
```Error occurred while enabling Waystones v1.0-1.16.3 (Is it up to date?)
java.lang.IllegalArgumentException: Crafting rows should be 1, 2, or 3 characters, not 12
        at org.apache.commons.lang.Validate.isTrue(Validate.java:93) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.inventory.ShapedRecipe.shape(ShapedRecipe.java:70) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at xyz.atrius.waystones.data.crafting.CraftingRecipe.setup(CraftingRecipe.kt:20) ~[?:?]
        at xyz.atrius.waystones.utility.PluginKt.registerRecipes(Plugin.kt:36) ~[?:?]
        at xyz.atrius.waystones.Waystones.onEnable(Waystones.kt:38) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3121-Spigot-66f9d3c-eeae1b1]
        at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by AtriusX** [comment]
There probably is room for improving the config side at least, but I believe it should be able to parse the current config string properly. The latter solution is definitely preferable though.

**Comment by AtriusX** [comment]
Seems like the property system relies on `toString()` to make the conversion to the config. This generally works well for simple data but I guess this doesn't translate well for list types. I'll see about making an adjustment to this in a bit.

**Comment by NathanAdhitya** [comment]
I've tried out the new commits. They are still spitting out errors for me for an existing config.

This is the migrated config from the previous (without key-recipe)
```
key-recipe:
- ''
- IRON_INGOT
- ''
- IRON_INGOT
- REDSTONE_BLOCK
- IRON_INGOT
- ''
- IRON_INGOT
- ''```

Could this be a platform issue? 🤔
I suppose a better mechanism to handle config-induced errors at startup would be nice. As it will make it possible to reload the configs later instead of the plugin failing to enable.

**Comment by AtriusX** [comment]
Probably will have to look into things a bit deeper I think. I'll see if I can deal with it soon, have been a bit busy lately.

**Comment by AtriusX** [comment]
I believe I fixed it, after testing it appears to work well. Apparently I forgot to convert the recipe's hashcodes back into chars so it was causing size problems.

**Comment by AtriusX** [comment]
@NathanAdhitya Able to check this for any other issues?

**Comment by NathanAdhitya** [comment]
Will check it soon. It's like midnight here and I must sleep, hahaha. Will give an update.

**Comment by AtriusX** [comment]
Alright thanks for the heads up

**Comment by NathanAdhitya** [comment]
Hello, I have tested it, the server ran properly. Perhaps tests should be in place to see if the plugin runs correctly in a server 😁. The new config entry is not displayed in /waystones config, but I suppose it is a simple fix.

There is an error during reloading, but it might be because of a stale branch.
```
org.bukkit.command.CommandException: Unhandled exception executing command 'waystones' in plugin Waystones v1.0-1.16.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: default localization file not in jar, corrupt download?
        at xyz.atrius.waystones.data.config.Localization.reload(Localization.kt:47) ~[?:?]
        at xyz.atrius.waystones.data.config.Config$locale$1.invoke(Config.kt:20) ~[?:?]
        at xyz.atrius.waystones.data.config.Config$locale$1.invoke(Config.kt) ~[?:?]
        at xyz.atrius.waystones.data.Property.invoke(Property.kt:33) ~[?:?]
        at xyz.atrius.waystones.data.config.ConfigManager.reload(ConfigManager.kt:31) ~[?:?]
        at xyz.atrius.waystones.commands.ReloadCommand.execute(ReloadCommand.kt:17) ~[?:?]
        at xyz.atrius.waystones.commands.CommandNamespace.onCommand(CommandNamespace.kt:34) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:3156-Spigot-cd36723-1c39efa]
        ... 19 more
```

**Comment by AtriusX** [comment]
From my testing the entry does display in the config but in order for it to be loaded you have to run `/waystones config` or `/waystones reload`. Attempts were made in the past to make this apply new settings to the config at startup but I couldn't get it working unfortunately.

The localization issue isn't something I've run into myself, so I would need a bit more information on how it occurred and if you can reproduce it.

I also pushed a few more adjustments to the config system so it would be a bit easier to follow and represent each item as the appropriate data type (it was apparently saving everything as a string before this).

**Comment by AtriusX** [comment]
@NathanAdhitya Have you tested the recent changes? Config values should be properly represented in-file now.

**Comment by NathanAdhitya** [comment]
Sorry for the long inactivity 😅.
I have tested this branch on a test server and everything seems to be working fine (so far).
I suppose more testing would be a good idea, I haven't really gotten time to validate the code.

**Comment by AtriusX** [comment]
I see, good to hear. Let me know if you want to take a bit more time to validate things, I'll probably merge it soon otherwise.

**Comment by NathanAdhitya** [comment]
Looks good enough at a glance. Unit tests for proving the stability would be more desirable, but I think this shall suffice.

**Comment by AtriusX** [comment]
Alright then, merging!

**Pull request merged**
