### PR TITLE
Fix JSON saving does not truncate the old file

### PR DESCRIPTION
**Pull request by NewbieOrange**
Fix saving broken JSON files if the new content is shorter than the older files.

### CODE REVIEW

**Comment by AtriusX** [comment]
There was definitely a weird JSON issue we couldn't reproduce in the past. Did you confirm that this fixes the issue? Also @Sepshun please double-check this as well.

**Comment by NewbieOrange** [comment]
Yes, I have tested it fixed my issue.

To reproduce the issue:
1. Have a clean state (empty json)
2. Rename a waystone
3. Destroy the waystone
4. Check the json file

**Comment by AtriusX** [comment]
Alright cool, once @Sepshun confirms then I'll merge the change.

**Comment by Sepshun** [comment]
Sorry it took so long, I'm pulling this to test right now though!

**Comment by Sepshun** [comment]
Tested and good to merge and close imo!

Though it's a little inconsistent compared to the bug we were facing, as in our case it would occur seemingly at random without having named a waystone at all, which made it quite difficult to track.
However, this change does fix the issue as far as I can tell!

**Pull request merged**
